version: "3"
services:
  frontend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ../frontend-app:/usr/src/app
    image: stylist_navi_frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=5000
